services:
  server:
    image: server
    build: .
    ports:
      - 8080:8080
    networks:
      - private
    depends_on:
      - db
    environment:
      - PORT=8080
      - DB_URL=postgres://postgres:admin@db:5432/postgres
    restart: unless-stopped
  db:
    image: postgres:16.4-alpine3.20
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    networks:
      - private
volumes:
  pgdata:
networks:
  private:
